title: "Tills Semester in Korea"
email: "tillhoffmann1411@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  Dies ist ein Blog 端ber Tills Semester in Korea. Hier teile ich Bilder und Eindr端cke aus Korea.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://till-in-korea.de"
domain: "till-in-korea.de"
permalink: "/:title"
site_logo: "/assets/images/logo.png"
white_logo: "/assets/images/logo-w.png"

copyright_text: "&copy; copyright all reserved to <a href='https://themefisher.com/'>themefisher.com</a>-2020"

author_info:
  - name: "Till Hoffmann"
    designation: "Wirtschaftsinformatik Student"
    bio: "Ich bin Till und bin aktuell f端r ein Auslandssemester in Ulsan in S端d Korea"
    image: "/assets/images/author.jpg"
    signature: "/assets/images/liammason.png"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-archives

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: "/category/:name/"
